name: Deploy Existing Image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to deploy (e.g. v1.2.3)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  prepare:
    runs-on: [mend-self-hosted, profile=sast-qa]
    outputs:
      TAG: ${{ steps.set-tag.outputs.TAG }}
    steps:
      - id: set-tag
        run: echo "TAG=${{ github.event.inputs.image_tag }}" >> "$GITHUB_OUTPUT"

  deploy-and-wait-for-sync:
    needs: [prepare]
    runs-on: [mend-self-hosted, profile=arch-small]
    env:
      IMAGE_TAG: ${{ needs.prepare.outputs.TAG }}
    steps:
      - name: Check out Mend helm-charts Repo
        uses: actions/checkout@v3
        with:
          repository: mend/helm-charts
          token: ${{ secrets.GH_TOKEN }}
          ref: main
          path: helm-charts-clone

      - name: Change image in helm chart values file
        run: |
          cd ./helm-charts-clone/values/reportportal-mcp-server/infra
          sed -i 's/tag: .*/tag: '"${IMAGE_TAG}"'/g' ./values-infra-dev.yaml
          git config --global user.name 'AutoRelease'
          git config --global user.email 'AutoRelease'
          git add .
          git commit -m "GH Actions AutoRelease ${IMAGE_TAG}" || echo "No changes to commit"
          git push
